import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Check, ArrowRight, Shield, Sparkles, Clock, Camera } from "lucide-react"
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Architect Headshots - AI Professional Headshots | SnapProHead',
  description: 'Get professional architect headshots in ~30 minutes. AI-generated photos starting at $29 for 40+ HD headshots. 14-day money-back guarantee.',
  openGraph: {
    title: 'Architect Headshots by SnapProHead',
    description: 'Professional architect headshots delivered in ~30 minutes. Starting at $29.',
  },
}

export default function ArchitectHeadshotsPage() {
  return (
    <div className="container px-4 md:px-6 py-16 md:py-24">
      {/* Hero */}
      <div className="mx-auto max-w-3xl text-center mb-16">
        <span className="inline-flex items-center px-3 py-1 rounded-full text-sm font-medium bg-primary/10 text-primary mb-4">
          Professional Architect Headshots
        </span>
        <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl mb-6">
          AI-Generated <span className="text-primary">Architect Headshots</span>
        </h1>
        <p className="text-muted-foreground text-lg md:text-xl max-w-[800px] mx-auto mb-8">
          Get professional architect headshots that make the right impression.
          Upload a few selfies and let our AI do the rest. Delivered in ~30 minutes.
        </p>
        <div className="flex flex-col sm:flex-row justify-center gap-4">
          <Link href="/login">
            <Button size="lg" className="gap-2 text-base px-8">
              Get Your Architect Headshots <ArrowRight className="h-4 w-4" />
            </Button>
          </Link>
        </div>
      </div>

      {/* Features */}
      <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-8 max-w-4xl mx-auto mb-20">
        <div className="flex flex-col items-center text-center p-6">
          <Sparkles className="h-10 w-10 text-primary mb-4" />
          <h3 className="font-semibold text-lg mb-2">AI-Powered Quality</h3>
          <p className="text-muted-foreground">Professional-grade headshots generated by advanced AI trained on thousands of professional photos.</p>
        </div>
        <div className="flex flex-col items-center text-center p-6">
          <Clock className="h-10 w-10 text-primary mb-4" />
          <h3 className="font-semibold text-lg mb-2">Delivered in ~30 Minutes</h3>
          <p className="text-muted-foreground">Upload your photos and get 40+ HD headshots in about 30 minutes. No appointment needed.</p>
        </div>
        <div className="flex flex-col items-center text-center p-6">
          <Camera className="h-10 w-10 text-primary mb-4" />
          <h3 className="font-semibold text-lg mb-2">Multiple Styles</h3>
          <p className="text-muted-foreground">Choose from corporate, natural, executive, and more styles. Get the look that fits your industry.</p>
        </div>
      </div>

      {/* Pricing CTA */}
      <div className="text-center bg-muted/30 rounded-2xl p-12 max-w-2xl mx-auto mb-20">
        <h2 className="text-3xl font-bold mb-4">Ready for Your Architect Headshots?</h2>
        <p className="text-muted-foreground text-lg mb-8">
          Starting at just $29 for 40+ HD headshots. 14-day money-back guarantee.
        </p>
        <Link href="/login">
          <Button size="lg" className="gap-2 text-base px-8">
            Get Started Now <ArrowRight className="h-4 w-4" />
          </Button>
        </Link>
      </div>

      {/* FAQ */}
      <div className="max-w-3xl mx-auto mb-8">
        <h2 className="text-2xl font-bold text-center mb-8">Frequently Asked Questions</h2>
        <div className="space-y-4">
          <details className="group border rounded-lg p-4">
            <summary className="font-medium cursor-pointer">How long does it take to get architect headshots?</summary>
            <p className="mt-2 text-muted-foreground">About 30 minutes. Upload 4-10 selfies and our AI generates 40+ professional headshots.</p>
          </details>
          <details className="group border rounded-lg p-4">
            <summary className="font-medium cursor-pointer">What kind of photos should I upload?</summary>
            <p className="mt-2 text-muted-foreground">Upload 4-10 clear selfies with different angles and expressions. Natural lighting works best.</p>
          </details>
          <details className="group border rounded-lg p-4">
            <summary className="font-medium cursor-pointer">How much do architect headshots cost?</summary>
            <p className="mt-2 text-muted-foreground">Starting at $29 for 40+ HD professional headshots. 14-day money-back guarantee.</p>
          </details>
        </div>
      </div>

      {/* Structured Data */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "Product",
            name: "Architect Headshots",
            description: "AI-generated professional architect headshots",
            offers: {
              "@type": "AggregateOffer",
              priceCurrency: "USD",
              lowPrice: "29",
              highPrice: "89",
              offerCount: "3",
            },
          }),
        }}
      />
    </div>
  )
}
